### ISSUE TITLE
How to add sensor state in notification message

### ISSUE THREAD

**Issue by nabulke** [resoai/TileBoard#232]
I try to add the state of a sensor in a notification message like that:

```
- id: '1558354218610'
  trigger:
  - entity_id: sensor.dwd_weather_warnings_current_warning_level
    from: '0'
    platform: state
  condition: []
  action:
  - event: tileboard
    event_data:
      command: notify
      data_template:
        message: 'State {{ states.sensor.dwd_weather_warnings_current_warning_level.state }}'
      type: warning
```
But it is not working. Anyone knows how to achieve this?

[More info](https://community.home-assistant.io/t/add-sensor-value-to-notification-message/117661?u=nabulke)
