### ISSUE TITLE
Floorplan for Home Assistant Tile

### ISSUE THREAD

**Issue by ekfuhrmann** [resoai/TileBoard#248]
Is it possible to make a [Floorplan](https://github.com/pkozul/ha-floorplan) tile in TileBoard?

![image](https://user-images.githubusercontent.com/8878152/62225230-073df000-b386-11e9-839d-9dd69ce29692.png)

In lovelace, I currently have a simple custom card with the following config:

```yaml
config:
  image: /local/floorplan/examples/simple/floorplan.svg
  rules:
    - entities:
        - media_player.living_room_tv
      states:
        - class: tv-off
          state: 'off'
        - class: tv-on
          state: 'on'
  stylesheet: /local/floorplan/examples/simple/simple.css?v=1.1.14
title: Simple Floorplan
type: 'custom:floorplan-card'
```

I’m unsure of whether or not there is any way to setup something similar inside of TileBoard?
