### ISSUE TITLE
Feature Request: Turn_on_action for media_players

### ISSUE THREAD

**Issue by nayaj** [resoai/TileBoard#25]
For my TV i use a command called Turn_on_action which basicly launches a WOL script i wrote.

Can this field be implemented into a media_player as optional?

```
turn_on_action:
  service: switch.turn_on
  data:
    entity_id: switch.LGTV
```

Cheers
