### ISSUE TITLE
bigger history chart

### ISSUE THREAD

**Issue by akloeckner** [resoai/TileBoard#300]
In my original implementation I could do the following to get a fullscreen popup also in portrait mode:
```
.history-popup-container::before {
  padding-bottom: 500%; /* fullscreen popup, was 75% */}
```
This does not work anymore. Somehow the `max-height` is not applied anymore. 

How can I achieve the desired effect in the new css framework, i.e. 100% height all the time?

@rchl

**Comment by rchl** [comment]
This should work.
```less
.history-popup {
   &-container {
      height: 100%;
   }

   &--canvas {
      height: ~'calc(100% - 50px)';
   }
}
```
I will have a look at how it worked before I've added title bar. Maybe I'll be able to simplify it (and break that css again ;)).
