### ISSUE TITLE
Door Entry Tile 

### ISSUE THREAD

**Issue by JDiaz11** [resoai/TileBoard#383]
Hello--

Great work! I'm wondering if the door entry tile pop-up is configurable to occur on a trigger rather than tap/click?
For example, when my doorbell rings (which causes a virtual contact sensor to open), I'd like the camera tile to open automatically so that it's already seeing the guest and prepped for interaction. Are you able to suggest how that may be accomplished or perhaps which file(s) require additional code? Thank you!

**Comment by resoai** [comment]
In HA automation you can send an event like this:

```
     ...
    action:
      - event: tileboard
        event_data:
          command: open_doorentry
          target: front_door
```

Than you would need to define the DOOR_ENTRY tile as a variable so you can reuse it and have something like this in the events:

```
 command: 'open_doorentry',
      action: function(eventData) {
         var tile = TILES.DOOR_ENTRY_FRONT_GATE;
         if(eventData.target === 'front_door') {
            tile = TILES.DOOR_ENTRY_FRONT_DOOR;
         }
         this.$scope.openDoorEntry(tile, tile.id);
```

In this example I'm including `target` just in case you have multiple door-entry devices like I do.
